### ISSUE TITLE
Activities admin panel

### ISSUE THREAD

**Issue by jbelien** [openknowledgebe/website#15]
Currently, the admin panel is split into "Activities Overview" and "Activities Pages".

If I understood correctly, an "activity overview" is the little activity box on the homepage and an "activity page" is the detailed page for an activity.

For me it seems confusing to have to create twice the information about an activity (once for the overview, once for the page), I asked @auloin about it in a previous PR : https://github.com/openknowledgebe/website/pull/10#discussion_r528170162

I would like to open the discussion here.
Do we have activities that won't have a dedicated page ?

**Comment by auloin** [comment]
> For me it seems confusing to have to create twice the information about an activity (once for the overview, once for the page)

The only repeated field is `name` . `Activities Pages` should be viewed as an extension of `Activities Overview` (the name isn't great).

**Comment by jbelien** [comment]
It has been decided during standup meeting (30/11/2020) to merge the 2 "admin panels".
