### ISSUE TITLE
Pinned stories on the homepage

### ISSUE THREAD

**Issue by jbelien** [openknowledgebe/website#28]
I like the fact that we can pin a story on the homepage but I think that every new story should automatically be displayed on the homepage (without needing to be manually pinned).

I would always display 3 stories : the pinned stories + the last published stories to make it always 3.

I personally also would increase the limit of 3 stories to 5 stories.

**Comment by auloin** [comment]
![image](https://user-images.githubusercontent.com/36740618/102059162-cd418280-3df0-11eb-912d-7f2335331eb2.png)
That's the issue with pinned stories... Activities also have an issue where the logo doesn't display in the preview.

**Comment by jbelien** [comment]
> That's the issue with pinned stories...

I would only display the story title (not the date), that should "fix" this problem.
I would also remove `date` from `search_fields`.

> Activities also have an issue where the logo doesn't display in the preview.

Indeed ^^
