### ISSUE TITLE
Small comments about page

### ISSUE THREAD

**Issue by SteenackersAstrid** [openknowledgebe/website#62]
- [x] first alinea: Open Knowledge Belgium is an umbrella organisation (non-profit/vzw/asbl) for numerous Open Knowledge initiatives in Belgium (no link here). We make knowledge sharing possible and let different organisations and individuals cross-pollinate. We’re one of the local chapters of the international Open Knowledge network (keep link here).
- [x] Make sure 'mission and vision', 'what is open knowledge', 'what is open data' get the same lay-out.
- [x] Add enter after what is open knowledge title
- [x] drop the state of open data in Belgium completely (won't be able to update information before release)

**Comment by jbelien** [comment]
Fixed by 328bcbd34790c71c702090a5fc7ce80401163223
