### ISSUE TITLE
Gatsby throws an error when there are no featured stories

### ISSUE THREAD

**Issue by auloin** [openknowledgebe/website#79]
This probably happens with featured activities as well.

See @jbelien's comment https://github.com/openknowledgebe/website/pull/76#pullrequestreview-555951985.

**Comment by auloin** [comment]
> This probably happens with featured activities as well.

I don't think there will be a case where there is no featured activity.

**Comment by jbelien** [comment]
> I don't think there will be a case where there is no featured activity.

Probably not but it's best it doesn't trigger an error if we decide (for some reason) to not pin any activity.
